name: jobs examples
on:
  push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: step do job build
        run: echo Hello, world! Build.
  job1:
    runs-on: ubuntu-latest
    steps:
    - name: step do job1
      run: echo Hello, world! job1.
  job2:
    runs-on: ubuntu-latest
    steps:
    - name: step do job2
      run: echo Hello, world! Job2.
      
  deploy:
      runs-on: ubuntu-latest
      needs: build
      steps:
      - name: step do deploy
        run: echo Hello, world! Deploy.
